pinojs/pino-std-serializers

Readme.md
lib/req.js
test/req.test.js

in order to integrate `stdSerializer` in to `hapi-pino` v4.x.x whilst keeping it consistent with current (and other ecosystem) implementations we have to 
* get hapi's req id from req.info
* get the url (equivalent) from req.url.path 
hopefully this doesn't penalize other loggers too much, we could create as sep. request serializer for hapi (maybe in pino-std-serializers) ?

hapi 17 support

---

Readme.md
lib/req.js
test/req.test.js

id defaults to undefined

---

lib/err.js
test/err.test.js

Nested errors with stack-traces can be a useful way of propagating error information. This PR enables recursively serializing nested errors while protecting against circular references.

err: support serializing nested errors

---

Readme.md
lib/res.js
test/res.test.js

Currently headers are not sent when logging a http response.
```javascript
log.child({ res }).debug('response!')
```
currently returns 
```json
{
"statusCode": 200,
"header": null
}
```
This `PR` makes sure that "headers" are sent instead of "header".
Also added a test 😄

serialize headers (renamed header to headers)

---

Readme.md

minor improvements to Readme as suggested in #19.

docs(Readme): make clear req.headers is a reference

---

lib/req.js
test/req.test.js

This fixes https://github.com/pinojs/pino-std-serializers/issues/21 by using `req.originalUrl` when available.

Fix serialized request url being wrong when using Express

---

lib/res.js

By Node.js documentation: 
```
The http module outgoingMessage._headers and outgoingMessage._headerNames properties are deprecated. Use one of the public methods (e.g. outgoingMessage.getHeader(), outgoingMessage.getHeaders(), outgoingMessage.getHeaderNames(), outgoingMessage.hasHeader(), outgoingMessage.removeHeader(), outgoingMessage.setHeader()) for working with outgoing headers.
```
It will fix `[DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated` warning message.

Fix #23 use getHeaders() instead of deprecated _headers

---

lib/req.js
test/req.test.js

[master] prefer req.path instead of req.url.path

---

lib/err.js
test/err.test.js

fixes potential crash in the serializer when err.constructor was modified by introducing a guard on err.constructor that verifies that err.constructor is an object, falls back to getting type from err.name in case this resolves negatively

fix: guard on err.constructor

---

lib/err.js
test/err.test.js

Pull #32 introduced a guard on err.constructor having been modified
such that it wasn't usable. However the comparison should be if it
is a *function*, not an object.
Before this change `_err.type` would also use the `: err.name` branch
of the ternary.

fix err.constructor guard: err.constructor is a function

---

lib/err-helpers.js
lib/err.js
package.json
test/err.test.js

Fixes #76, see that for a description 
I did some other tweaks at #77, which I needed to get this patch working locally

Serialize `err.cause` in a nice way when possible

---

lib/err.js
package.json
test/err.test.js

Example
```js
const log = require('pino')()
const foo = new Error('foo')
const bar = new Error('bar')
const aggregate = new AggregateError([foo, bar], 'aggregated message')
log.error(aggregate)
```
Produces the following serialized output:
```json
{
"level": 50,
"time": 1641313649352,
"pid": 1788,
"hostname": "SAMEER",
"err": {
"type": "AggregateError",
"message": "aggregated message",
"stack": "AggregateError: aggregated message\n at Object.<anonymous> (pino-std-serializers\\example.js:12:19)\n at Module._compile (node:internal/modules/cjs/loader:1108:14)\n at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)\n at Module.load (node:internal/modules/cjs/loader:988:32)\n at Function.Module._load (node:internal/modules/cjs/loader:828:14)\n at …
```

Support for aggregate errors

---

lib/req.js
test/req.test.js

only use `req.path` if it is a string. this is for restify compatibility; fixes #88.
in #29 we preferred `req.path`, because `req.url` would throw in hapi if the path was invalid.
in restify though, [`req.path` is a function](https://github.com/restify/node-restify/blob/5c7eb95319aa54ef3b4b60d000d434824a666e18/lib/request.js#L357) (which returns a parsed url object). so after #29, restify stopped logging url.
in this pr, we check `req.path` to see if it is a string before using it. else we go back to using `req.url`. alternatively, we could have checked if path was a function, then checked if the object returned had a path element, but simply being more specific about what `req.path`'s we accept was preferred as it reduced the amount of branches the code would take.
i have also added a …

Fix restify (#88) by only using req.path if a string

---

Readme.md
lib/req.js
test/req.test.js

Presently `req.params` and `req.query` are only included for express. These changes add support for those properties in similar frameworks such as hapi.

Include req.params and req.query when available

---

.taprc
package.json

This fixes #104 where the glob for picking test files meant that the test script did not work at all on Windows.

Move file specification for test script to .taprc

---

lib/err.js
test/err.test.js

Related to #76 and #78 which add serialization of `cause` into error messages.
This PR fixes #94 by making sure the chain of causes found in `err.cause` is serialized in full, bringing the final serialized result closer to what is printed by other serializers (e.g. those in the Node.js CLI and browser consoles).

Serialize errors with cause

---

lib/err-helpers.js
lib/err.js
test/err.test.js

It was bugging me that I had left out support for VError-style errors that are supported elsewhere when I made #105, so here's a PR adding support for that :smile:

Nested VError causes

---

lib/err-helpers.js
lib/err.js
test/err.test.js

This is an alternative fix to #94, replacing #105 and #108 and in the process make #109 not needed
Builds on my comment here https://github.com/pinojs/pino-std-serializers/pull/105#issuecomment-1153917121
In short:
Doing both a summary of the errors cause chain + serializing all the errors in the cause chain is doing the same thing twice basically.
And when on top of that doing summaries for each cause along the chain as well, then that's triple work.
In https://github.com/pinojs/pino-std-serializers/pull/78/files#diff-71c187d84f435004e68161a25e470d823f4de310a1d39b531cc02a90f3730149R56 I specifically opted out causes from recursion:
```javascript
if (val instanceof Error && key !== 'cause') {
/* eslint-disable no-prototype-builtins */
if (!val.hasOwnProperty(seen)) {
```
I think #94 …

Never serialize `.cause` Errors, rely on message + stack summary instead

---

.github/workflows/ci.yml

BREAKING CHANGE: Drops support for EOL node 10, 12 and 15; adds support for node 18

chore!: drop support for node 10, 12 and 15; add support for node 18

---

Readme.md
index.d.ts
index.js
lib/err-helpers.js
lib/err-proto.js
lib/err-with-cause.js
lib/err.js
test/err-with-cause.test.js
test/types/index.test-d.ts
tsconfig.json

- Created new serializer called "errWithCause". This serializer acts very similarly to the default "err" serializer. The differences: When it encounters an "error.cause" field, it serializes it recursively to create a nested object of errors. This is as opposed to the default error serializer, in which the resulting serialized object has no "cause" field, and the causes' messages & stack traces are appended to the original error.message and error.stack
- Since some logic is reused between the existing err serializer and the new one, I moved some logic to the err-helpers file
- Created a test-file for the new serializer. It is very similar to the existing err serializer test file since they should behave nearly identically. The differences are in the tests that test for the "cause" related …

feat(serializers): Implemented "error with cause" serializer

---

index.d.ts

Adds info that `cause` is always undefined.
- I was confused, I guess I missed that `[string]: any` and interpreted this as `.cause` being supposed to be set.
- <img width="724" alt="CleanShot 2023-02-07 at 19 01 55@2x" src="https://user-images.githubusercontent.com/459267/217328824-639a7685-baa9-435c-a856-6472e4223c14.png">
- https://github.com/pinojs/pino-std-serializers/pull/123
- #110
I am not sure if I agree with the decision to hide it, the original issue (#94), seemed to want explicit handling of `.cause` and not to hide it. It caught me by surprise.

Add info about `cause` explicitly always being `undefined`

---

index.d.ts
test/types/index.test-d.ts

[params](https://github.com/pinojs/pino-std-serializers/blob/master/lib/req.js#L30) and [query](https://github.com/pinojs/pino-std-serializers/blob/master/lib/req.js#L25) are listed as part of serialized request object but missing in the [SerializedRequest](https://github.com/pinojs/pino-std-serializers/blob/master/index.d.ts#L49) interface

Add params and query to ts definition

---

.github/workflows/ci.yml
package.json

Hello everyone!
As needed in [issue #1762](https://github.com/pinojs/pino/issues/1762) and referenced [here](https://github.com/pinojs/pino-http/issues/299) this pr is needed for pino v9.
I did not open an issue related but I will if needed, and I merged both CI and dependencies update, if you think it's better to provide two separate pr, I'll split them as well.
Thank you in advance!
@jsumners

Updating for v9: update dependencies and CI

---

Readme.md

Readme.md markdown around the `exports.errWithCause(error)` documentation is rendering wrong because the previous code block is not closed

docs(readme): add missing code block quotes
